[build]
  base = "/"
  publish = "staticfiles"
  command = """
    curl https://pyenv.run | bash
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    pyenv install 3.9.18
    pyenv global 3.9.18
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  """

[build.environment]
  NODE_VERSION = "18"
  PIPENV_VENV_IN_PROJECT = "true"
  PYTHON_VERSION = "3.9.18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/django-api/:splat"
  status = 200
  force = true 