[build]
  base = "/"
  publish = "staticfiles"
  command = "npm run build"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/django-api/:splat"
  status = 200
  force = true 