# Generated by Django 5.0.2 on 2025-06-20 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_refundlog_reason'),
    ]

    operations = [
        # This migration was causing issues with UUID conversion
        # The chart model already has the correct structure with uuid field
        # No changes needed - this is a no-op migration
    ]
