# Generated by Django 4.2.23 on 2025-07-20 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_chart_has_preview_version_chart_preview_chart_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
